# Generated by Django 5.0 on 2024-01-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvasimage',
            name='image',
            field=models.TextField(),
        ),
    ]
