# Generated by Django 5.0 on 2024-01-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_canvasimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvasimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
